import { expect, test } from './fixtures'

test('draf soal tersimpan otomatis dan bisa dipulihkan setelah reload', async ({ page }) => {
  await page.route('**/api/**', async (route) => {
    const request = route.request()
    const path = new URL(request.url()).pathname.replace('/api', '')
    if (path === '/public/config') return route.fulfill({ json: { formsEnabled: false } })
    const method = request.method()
    const json = (data: unknown, status = 200) => route.fulfill({ status, json: data })
    if (path === '/auth/login' && method === 'POST') return json({ accessToken: 'staff-session', user: { id: 'teacher-1', username: 'tutor', nama: 'Tutor Uji', role: 'guru' } })
    if (path === '/staff/questions' && method === 'GET') return json([])
    if (path === '/staff/trash' && method === 'GET') return json({ questions: [], assessments: [] })
    if (path === '/staff/archive' && method === 'GET') return json({ questions: [], assessments: [] })
    return json({ error: `Unmocked request: ${method} ${path}` }, 500)
  })

  await page.goto('/')
  await page.getByRole('button', { name: 'Tutor / Admin' }).click()
  await page.getByLabel('Username CBT').fill('tutor')
  await page.getByLabel('Kata sandi').fill('secret')
  await page.getByRole('button', { name: 'Masuk ke workspace' }).click()
  await page.getByRole('button', { name: 'Bank Soal' }).click()
  await page.getByRole('link', { name: 'Pustaka soal lepas' }).click()
  await page.getByRole('button', { name: 'Buat soal' }).click()
  await page.getByRole('button', { name: 'Mulai sederhana' }).click()
  await page.getByLabel('Judul soal (opsional)').fill('Daur air')
  await page.getByLabel('Pertanyaan').fill('Bagaimana air hujan terbentuk?')
  await expect(page.getByText('Tersimpan otomatis di perangkat ini ✓')).toBeVisible({ timeout: 5000 })

  await page.getByRole('button', { name: 'Tutup editor' }).click()
  await page.getByRole('button', { name: 'Buat soal' }).click()
  await page.getByRole('button', { name: 'Mulai sederhana' }).click()
  await expect(page.getByLabel('Pertanyaan')).toHaveValue('Bagaimana air hujan terbentuk?')

  await page.reload()
  await page.getByRole('button', { name: 'Bank Soal' }).click()
  await page.getByRole('link', { name: 'Pustaka soal lepas' }).click()
  await page.getByRole('button', { name: 'Buat soal' }).click()
  await page.getByRole('button', { name: 'Mulai sederhana' }).click()
  await expect(page.getByText('Draf lokal dipulihkan. Lanjutkan, lalu simpan ke Bank Soal.')).toBeVisible()
  await expect(page.getByLabel('Judul soal (opsional)')).toHaveValue('Daur air')
  await expect(page.getByLabel('Pertanyaan')).toHaveValue('Bagaimana air hujan terbentuk?')
})
